// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: robot.proto

package robot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Identity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdentityId string `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc       string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *Identity) Reset() {
	*x = Identity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *Identity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Identity) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagId   string `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc    string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Words   string `protobuf:"bytes,4,opt,name=words,proto3" json:"words,omitempty"`
	Exclude string `protobuf:"bytes,5,opt,name=exclude,proto3" json:"exclude,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Tag) GetWords() string {
	if x != nil {
		return x.Words
	}
	return ""
}

func (x *Tag) GetExclude() string {
	if x != nil {
		return x.Exclude
	}
	return ""
}

type Gender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GenderId uint32 `protobuf:"varint,1,opt,name=gender_id,json=genderId,proto3" json:"gender_id,omitempty"`
	NameEn   string `protobuf:"bytes,2,opt,name=name_en,json=nameEn,proto3" json:"name_en,omitempty"`
	NameCn   string `protobuf:"bytes,3,opt,name=name_cn,json=nameCn,proto3" json:"name_cn,omitempty"`
	Desc     string `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
}

func (x *Gender) Reset() {
	*x = Gender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gender) ProtoMessage() {}

func (x *Gender) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gender.ProtoReflect.Descriptor instead.
func (*Gender) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{2}
}

func (x *Gender) GetGenderId() uint32 {
	if x != nil {
		return x.GenderId
	}
	return 0
}

func (x *Gender) GetNameEn() string {
	if x != nil {
		return x.NameEn
	}
	return ""
}

func (x *Gender) GetNameCn() string {
	if x != nil {
		return x.NameCn
	}
	return ""
}

func (x *Gender) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type GetGenderListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGenderListReq) Reset() {
	*x = GetGenderListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenderListReq) ProtoMessage() {}

func (x *GetGenderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenderListReq.ProtoReflect.Descriptor instead.
func (*GetGenderListReq) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{3}
}

type GetGenderListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GenderList []*Gender `protobuf:"bytes,1,rep,name=gender_list,json=genderList,proto3" json:"gender_list,omitempty"`
}

func (x *GetGenderListRsp) Reset() {
	*x = GetGenderListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenderListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenderListRsp) ProtoMessage() {}

func (x *GetGenderListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenderListRsp.ProtoReflect.Descriptor instead.
func (*GetGenderListRsp) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{4}
}

func (x *GetGenderListRsp) GetGenderList() []*Gender {
	if x != nil {
		return x.GenderList
	}
	return nil
}

type GetIdentityListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetIdentityListReq) Reset() {
	*x = GetIdentityListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdentityListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityListReq) ProtoMessage() {}

func (x *GetIdentityListReq) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityListReq.ProtoReflect.Descriptor instead.
func (*GetIdentityListReq) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{5}
}

type GetIdentityListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdentityList []*Identity `protobuf:"bytes,1,rep,name=identity_list,json=identityList,proto3" json:"identity_list,omitempty"`
}

func (x *GetIdentityListRsp) Reset() {
	*x = GetIdentityListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdentityListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityListRsp) ProtoMessage() {}

func (x *GetIdentityListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityListRsp.ProtoReflect.Descriptor instead.
func (*GetIdentityListRsp) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{6}
}

func (x *GetIdentityListRsp) GetIdentityList() []*Identity {
	if x != nil {
		return x.IdentityList
	}
	return nil
}

type GetTagListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SelectedTagIds []string `protobuf:"bytes,1,rep,name=selected_tag_ids,json=selectedTagIds,proto3" json:"selected_tag_ids,omitempty"`
}

func (x *GetTagListReq) Reset() {
	*x = GetTagListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagListReq) ProtoMessage() {}

func (x *GetTagListReq) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagListReq.ProtoReflect.Descriptor instead.
func (*GetTagListReq) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{7}
}

func (x *GetTagListReq) GetSelectedTagIds() []string {
	if x != nil {
		return x.SelectedTagIds
	}
	return nil
}

type GetTagListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TagList []*Tag `protobuf:"bytes,1,rep,name=tag_list,json=tagList,proto3" json:"tag_list,omitempty"`
}

func (x *GetTagListRsp) Reset() {
	*x = GetTagListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagListRsp) ProtoMessage() {}

func (x *GetTagListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagListRsp.ProtoReflect.Descriptor instead.
func (*GetTagListRsp) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{8}
}

func (x *GetTagListRsp) GetTagList() []*Tag {
	if x != nil {
		return x.TagList
	}
	return nil
}

type Robot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId        string        `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	UserId         string        `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name           string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar         string        `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Age            uint32        `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Gender         uint32        `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Location       string        `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	IdentityId     string        `protobuf:"bytes,8,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`              // 身份
	TagId          string        `protobuf:"bytes,9,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`                             // 标签, 逗号分隔
	CustomIdentity *Identity     `protobuf:"bytes,10,opt,name=custom_identity,json=customIdentity,proto3" json:"custom_identity,omitempty"` // 自定义身份
	CustomTag      []*Tag        `protobuf:"bytes,11,rep,name=custom_tag,json=customTag,proto3" json:"custom_tag,omitempty"`                // 自定义标签
	CreateTime     int64         `protobuf:"varint,20,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Dynamic        *RobotDynamic `protobuf:"bytes,100,opt,name=dynamic,proto3" json:"dynamic,omitempty"`
}

func (x *Robot) Reset() {
	*x = Robot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Robot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Robot) ProtoMessage() {}

func (x *Robot) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Robot.ProtoReflect.Descriptor instead.
func (*Robot) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{9}
}

func (x *Robot) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *Robot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Robot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Robot) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Robot) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Robot) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *Robot) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Robot) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *Robot) GetTagId() string {
	if x != nil {
		return x.TagId
	}
	return ""
}

func (x *Robot) GetCustomIdentity() *Identity {
	if x != nil {
		return x.CustomIdentity
	}
	return nil
}

func (x *Robot) GetCustomTag() []*Tag {
	if x != nil {
		return x.CustomTag
	}
	return nil
}

func (x *Robot) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Robot) GetDynamic() *RobotDynamic {
	if x != nil {
		return x.Dynamic
	}
	return nil
}

type RobotDynamic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score     int32  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`                          // 积分
	GameTotal uint32 `protobuf:"varint,2,opt,name=game_total,json=gameTotal,proto3" json:"game_total,omitempty"` // 总场数
	GameWin   uint32 `protobuf:"varint,3,opt,name=game_win,json=gameWin,proto3" json:"game_win,omitempty"`       // 胜利数
}

func (x *RobotDynamic) Reset() {
	*x = RobotDynamic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RobotDynamic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotDynamic) ProtoMessage() {}

func (x *RobotDynamic) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotDynamic.ProtoReflect.Descriptor instead.
func (*RobotDynamic) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{10}
}

func (x *RobotDynamic) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RobotDynamic) GetGameTotal() uint32 {
	if x != nil {
		return x.GameTotal
	}
	return 0
}

func (x *RobotDynamic) GetGameWin() uint32 {
	if x != nil {
		return x.GameWin
	}
	return 0
}

type RobotDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId      string      `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Gender       *Gender     `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	IdentityList []*Identity `protobuf:"bytes,3,rep,name=identity_list,json=identityList,proto3" json:"identity_list,omitempty"`
	TagList      []*Tag      `protobuf:"bytes,4,rep,name=tag_list,json=tagList,proto3" json:"tag_list,omitempty"`
}

func (x *RobotDetail) Reset() {
	*x = RobotDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RobotDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotDetail) ProtoMessage() {}

func (x *RobotDetail) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotDetail.ProtoReflect.Descriptor instead.
func (*RobotDetail) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{11}
}

func (x *RobotDetail) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *RobotDetail) GetGender() *Gender {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *RobotDetail) GetIdentityList() []*Identity {
	if x != nil {
		return x.IdentityList
	}
	return nil
}

func (x *RobotDetail) GetTagList() []*Tag {
	if x != nil {
		return x.TagList
	}
	return nil
}

type GetRobotReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId string `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
}

func (x *GetRobotReq) Reset() {
	*x = GetRobotReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRobotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRobotReq) ProtoMessage() {}

func (x *GetRobotReq) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRobotReq.ProtoReflect.Descriptor instead.
func (*GetRobotReq) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{12}
}

func (x *GetRobotReq) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type GetRobotRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Robot *Robot `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
}

func (x *GetRobotRsp) Reset() {
	*x = GetRobotRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRobotRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRobotRsp) ProtoMessage() {}

func (x *GetRobotRsp) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRobotRsp.ProtoReflect.Descriptor instead.
func (*GetRobotRsp) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{13}
}

func (x *GetRobotRsp) GetRobot() *Robot {
	if x != nil {
		return x.Robot
	}
	return nil
}

type GetRobotDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId string `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
}

func (x *GetRobotDetailReq) Reset() {
	*x = GetRobotDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRobotDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRobotDetailReq) ProtoMessage() {}

func (x *GetRobotDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRobotDetailReq.ProtoReflect.Descriptor instead.
func (*GetRobotDetailReq) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{14}
}

func (x *GetRobotDetailReq) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type GetRobotDetailRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Robot  *Robot       `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
	Detail *RobotDetail `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
}

func (x *GetRobotDetailRsp) Reset() {
	*x = GetRobotDetailRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRobotDetailRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRobotDetailRsp) ProtoMessage() {}

func (x *GetRobotDetailRsp) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRobotDetailRsp.ProtoReflect.Descriptor instead.
func (*GetRobotDetailRsp) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{15}
}

func (x *GetRobotDetailRsp) GetRobot() *Robot {
	if x != nil {
		return x.Robot
	}
	return nil
}

func (x *GetRobotDetailRsp) GetDetail() *RobotDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type NewRobotReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Robot *Robot `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
}

func (x *NewRobotReq) Reset() {
	*x = NewRobotReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRobotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRobotReq) ProtoMessage() {}

func (x *NewRobotReq) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRobotReq.ProtoReflect.Descriptor instead.
func (*NewRobotReq) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{16}
}

func (x *NewRobotReq) GetRobot() *Robot {
	if x != nil {
		return x.Robot
	}
	return nil
}

type NewRobotRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Robot *Robot `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
}

func (x *NewRobotRsp) Reset() {
	*x = NewRobotRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRobotRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRobotRsp) ProtoMessage() {}

func (x *NewRobotRsp) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRobotRsp.ProtoReflect.Descriptor instead.
func (*NewRobotRsp) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{17}
}

func (x *NewRobotRsp) GetRobot() *Robot {
	if x != nil {
		return x.Robot
	}
	return nil
}

type EditRobotReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Robot *Robot `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
}

func (x *EditRobotReq) Reset() {
	*x = EditRobotReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditRobotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditRobotReq) ProtoMessage() {}

func (x *EditRobotReq) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditRobotReq.ProtoReflect.Descriptor instead.
func (*EditRobotReq) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{18}
}

func (x *EditRobotReq) GetRobot() *Robot {
	if x != nil {
		return x.Robot
	}
	return nil
}

type EditRobotRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Robot *Robot `protobuf:"bytes,1,opt,name=robot,proto3" json:"robot,omitempty"`
}

func (x *EditRobotRsp) Reset() {
	*x = EditRobotRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditRobotRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditRobotRsp) ProtoMessage() {}

func (x *EditRobotRsp) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditRobotRsp.ProtoReflect.Descriptor instead.
func (*EditRobotRsp) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{19}
}

func (x *EditRobotRsp) GetRobot() *Robot {
	if x != nil {
		return x.Robot
	}
	return nil
}

type DeleteRobotReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId string `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
}

func (x *DeleteRobotReq) Reset() {
	*x = DeleteRobotReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRobotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRobotReq) ProtoMessage() {}

func (x *DeleteRobotReq) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRobotReq.ProtoReflect.Descriptor instead.
func (*DeleteRobotReq) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteRobotReq) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type DeleteRobotRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRobotRsp) Reset() {
	*x = DeleteRobotRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRobotRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRobotRsp) ProtoMessage() {}

func (x *DeleteRobotRsp) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRobotRsp.ProtoReflect.Descriptor instead.
func (*DeleteRobotRsp) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{21}
}

type GetMyRobotsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMyRobotsReq) Reset() {
	*x = GetMyRobotsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyRobotsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyRobotsReq) ProtoMessage() {}

func (x *GetMyRobotsReq) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyRobotsReq.ProtoReflect.Descriptor instead.
func (*GetMyRobotsReq) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{22}
}

type GetMyRobotsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Robots []*Robot `protobuf:"bytes,1,rep,name=robots,proto3" json:"robots,omitempty"`
}

func (x *GetMyRobotsRsp) Reset() {
	*x = GetMyRobotsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMyRobotsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyRobotsRsp) ProtoMessage() {}

func (x *GetMyRobotsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyRobotsRsp.ProtoReflect.Descriptor instead.
func (*GetMyRobotsRsp) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{23}
}

func (x *GetMyRobotsRsp) GetRobots() []*Robot {
	if x != nil {
		return x.Robots
	}
	return nil
}

type RecommendRobotsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RecommendRobotsReq) Reset() {
	*x = RecommendRobotsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendRobotsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRobotsReq) ProtoMessage() {}

func (x *RecommendRobotsReq) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRobotsReq.ProtoReflect.Descriptor instead.
func (*RecommendRobotsReq) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{24}
}

type RecommendRobotsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Robots []*Robot `protobuf:"bytes,1,rep,name=robots,proto3" json:"robots,omitempty"`
}

func (x *RecommendRobotsRsp) Reset() {
	*x = RecommendRobotsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendRobotsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendRobotsRsp) ProtoMessage() {}

func (x *RecommendRobotsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendRobotsRsp.ProtoReflect.Descriptor instead.
func (*RecommendRobotsRsp) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{25}
}

func (x *RecommendRobotsRsp) GetRobots() []*Robot {
	if x != nil {
		return x.Robots
	}
	return nil
}

type RandomRobotIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RandomRobotIDReq) Reset() {
	*x = RandomRobotIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomRobotIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomRobotIDReq) ProtoMessage() {}

func (x *RandomRobotIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomRobotIDReq.ProtoReflect.Descriptor instead.
func (*RandomRobotIDReq) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{26}
}

type RandomRobotIDRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId string `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
}

func (x *RandomRobotIDRsp) Reset() {
	*x = RandomRobotIDRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomRobotIDRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomRobotIDRsp) ProtoMessage() {}

func (x *RandomRobotIDRsp) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomRobotIDRsp.ProtoReflect.Descriptor instead.
func (*RandomRobotIDRsp) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{27}
}

func (x *RandomRobotIDRsp) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type UpdateDynamicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId string        `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Dynamic *RobotDynamic `protobuf:"bytes,2,opt,name=dynamic,proto3" json:"dynamic,omitempty"`
}

func (x *UpdateDynamicReq) Reset() {
	*x = UpdateDynamicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDynamicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDynamicReq) ProtoMessage() {}

func (x *UpdateDynamicReq) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDynamicReq.ProtoReflect.Descriptor instead.
func (*UpdateDynamicReq) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateDynamicReq) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *UpdateDynamicReq) GetDynamic() *RobotDynamic {
	if x != nil {
		return x.Dynamic
	}
	return nil
}

type UpdateDynamicRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateDynamicRsp) Reset() {
	*x = UpdateDynamicRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_robot_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDynamicRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDynamicRsp) ProtoMessage() {}

func (x *UpdateDynamicRsp) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDynamicRsp.ProtoReflect.Descriptor instead.
func (*UpdateDynamicRsp) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{29}
}

var File_robot_proto protoreflect.FileDescriptor

var file_robot_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x74,
	0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x22, 0x53, 0x0a, 0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x74, 0x0a, 0x03, 0x54, 0x61,
	0x67, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x61, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65,
	0x22, 0x6b, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x67,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x61, 0x6d, 0x65, 0x5f,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x61, 0x6d, 0x65, 0x45, 0x6e,
	0x12, 0x17, 0x0a, 0x07, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x63, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x61, 0x6d, 0x65, 0x43, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73,
	0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0x12, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x22, 0x53, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0b, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x74, 0x75, 0x72,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x0a, 0x67, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x5b, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x73, 0x70, 0x12, 0x45, 0x0a, 0x0d, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x75, 0x72, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0c, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x54, 0x61,
	0x67, 0x49, 0x64, 0x73, 0x22, 0x47, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x2e, 0x54, 0x61, 0x67, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xcd, 0x03,
	0x0a, 0x05, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a,
	0x0b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x15,
	0x0a, 0x06, 0x74, 0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x61, 0x67, 0x49, 0x64, 0x12, 0x49, 0x0a, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x0e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x0b,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x54, 0x61,
	0x67, 0x52, 0x09, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x61, 0x67, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3e, 0x0a,
	0x07, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x44, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x52, 0x07, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x22, 0x5e, 0x0a,
	0x0c, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x77, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x57, 0x69, 0x6e, 0x22, 0xdf, 0x01,
	0x0a, 0x0b, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x0a,
	0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e,
	0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x45, 0x0a, 0x0d, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0c, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x75, 0x72, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x2e, 0x54, 0x61, 0x67, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x28, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x05, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x05, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x22, 0x2e, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x85, 0x01,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x05, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x52, 0x6f, 0x62, 0x6f,
	0x74, 0x52, 0x05, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e,
	0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x42, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x52, 0x6f, 0x62, 0x6f,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x05, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x52, 0x6f, 0x62,
	0x6f, 0x74, 0x52, 0x05, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x22, 0x42, 0x0a, 0x0b, 0x4e, 0x65, 0x77,
	0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x05, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x05, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x22, 0x43, 0x0a,
	0x0c, 0x45, 0x64, 0x69, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x12, 0x33, 0x0a,
	0x05, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74,
	0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x05, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x22, 0x43, 0x0a, 0x0c, 0x45, 0x64, 0x69, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52,
	0x73, 0x70, 0x12, 0x33, 0x0a, 0x05, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74,
	0x52, 0x05, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x22, 0x2b, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f,
	0x62, 0x6f, 0x74, 0x52, 0x73, 0x70, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x22, 0x47, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d,
	0x79, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x06, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x74, 0x75, 0x72,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x06, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x73, 0x22, 0x14, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x52, 0x6f,
	0x62, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x22, 0x4b, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x35, 0x0a,
	0x06, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x06, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x6f,
	0x62, 0x6f, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x22, 0x2d, 0x0a, 0x10, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x44, 0x52, 0x73, 0x70, 0x12, 0x19, 0x0a, 0x08,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x6d, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x72,
	0x6f, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72,
	0x6f, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x07, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x2e, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x07, 0x64,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x73, 0x70, 0x32, 0x96, 0x09, 0x0a, 0x08, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x53, 0x76, 0x72, 0x12, 0x63, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x47, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e,
	0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x28, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x47,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x69, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x2a, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x2a, 0x2e, 0x74, 0x75,
	0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72,
	0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x5a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72,
	0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x74,
	0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x54, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12,
	0x23, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x62, 0x6f,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x73, 0x70, 0x12, 0x66, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x52, 0x6f, 0x62, 0x6f, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x29, 0x2e, 0x74, 0x75,
	0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72,
	0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x29, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65,
	0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x73,
	0x70, 0x12, 0x54, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12, 0x23, 0x2e,
	0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x4e, 0x65, 0x77, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x23, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x4e, 0x65, 0x77, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x52, 0x73, 0x70, 0x12, 0x57, 0x0a, 0x09, 0x45, 0x64, 0x69, 0x74, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x12, 0x24, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x45, 0x64,
	0x69, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x74, 0x75, 0x72,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x73, 0x70,
	0x12, 0x5d, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x12,
	0x26, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x73, 0x70, 0x12,
	0x5d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x12, 0x26,
	0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x79, 0x52, 0x6f, 0x62,
	0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x26, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65,
	0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x4d, 0x79, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x69,
	0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x52, 0x6f, 0x62, 0x6f, 0x74,
	0x73, 0x12, 0x2a, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x2a, 0x2e,
	0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64,
	0x52, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x63, 0x0a, 0x0d, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x44, 0x12, 0x28, 0x2e, 0x74, 0x75, 0x72,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f,
	0x62, 0x6f, 0x74, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x52, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x44, 0x52, 0x73, 0x70, 0x12, 0x63,
	0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12,
	0x28, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x28, 0x2e, 0x74, 0x75, 0x72, 0x69,
	0x6e, 0x67, 0x65, 0x72, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x72, 0x6f, 0x62,
	0x6f, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x52, 0x73, 0x70, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x2d, 0x65, 0x72, 0x61, 0x2f, 0x74, 0x75, 0x72,
	0x69, 0x6e, 0x67, 0x65, 0x72, 0x61, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_robot_proto_rawDescOnce sync.Once
	file_robot_proto_rawDescData = file_robot_proto_rawDesc
)

func file_robot_proto_rawDescGZIP() []byte {
	file_robot_proto_rawDescOnce.Do(func() {
		file_robot_proto_rawDescData = protoimpl.X.CompressGZIP(file_robot_proto_rawDescData)
	})
	return file_robot_proto_rawDescData
}

var file_robot_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_robot_proto_goTypes = []interface{}{
	(*Identity)(nil),           // 0: turingera.server.robot.Identity
	(*Tag)(nil),                // 1: turingera.server.robot.Tag
	(*Gender)(nil),             // 2: turingera.server.robot.Gender
	(*GetGenderListReq)(nil),   // 3: turingera.server.robot.GetGenderListReq
	(*GetGenderListRsp)(nil),   // 4: turingera.server.robot.GetGenderListRsp
	(*GetIdentityListReq)(nil), // 5: turingera.server.robot.GetIdentityListReq
	(*GetIdentityListRsp)(nil), // 6: turingera.server.robot.GetIdentityListRsp
	(*GetTagListReq)(nil),      // 7: turingera.server.robot.GetTagListReq
	(*GetTagListRsp)(nil),      // 8: turingera.server.robot.GetTagListRsp
	(*Robot)(nil),              // 9: turingera.server.robot.Robot
	(*RobotDynamic)(nil),       // 10: turingera.server.robot.RobotDynamic
	(*RobotDetail)(nil),        // 11: turingera.server.robot.RobotDetail
	(*GetRobotReq)(nil),        // 12: turingera.server.robot.GetRobotReq
	(*GetRobotRsp)(nil),        // 13: turingera.server.robot.GetRobotRsp
	(*GetRobotDetailReq)(nil),  // 14: turingera.server.robot.GetRobotDetailReq
	(*GetRobotDetailRsp)(nil),  // 15: turingera.server.robot.GetRobotDetailRsp
	(*NewRobotReq)(nil),        // 16: turingera.server.robot.NewRobotReq
	(*NewRobotRsp)(nil),        // 17: turingera.server.robot.NewRobotRsp
	(*EditRobotReq)(nil),       // 18: turingera.server.robot.EditRobotReq
	(*EditRobotRsp)(nil),       // 19: turingera.server.robot.EditRobotRsp
	(*DeleteRobotReq)(nil),     // 20: turingera.server.robot.DeleteRobotReq
	(*DeleteRobotRsp)(nil),     // 21: turingera.server.robot.DeleteRobotRsp
	(*GetMyRobotsReq)(nil),     // 22: turingera.server.robot.GetMyRobotsReq
	(*GetMyRobotsRsp)(nil),     // 23: turingera.server.robot.GetMyRobotsRsp
	(*RecommendRobotsReq)(nil), // 24: turingera.server.robot.RecommendRobotsReq
	(*RecommendRobotsRsp)(nil), // 25: turingera.server.robot.RecommendRobotsRsp
	(*RandomRobotIDReq)(nil),   // 26: turingera.server.robot.RandomRobotIDReq
	(*RandomRobotIDRsp)(nil),   // 27: turingera.server.robot.RandomRobotIDRsp
	(*UpdateDynamicReq)(nil),   // 28: turingera.server.robot.UpdateDynamicReq
	(*UpdateDynamicRsp)(nil),   // 29: turingera.server.robot.UpdateDynamicRsp
}
var file_robot_proto_depIdxs = []int32{
	2,  // 0: turingera.server.robot.GetGenderListRsp.gender_list:type_name -> turingera.server.robot.Gender
	0,  // 1: turingera.server.robot.GetIdentityListRsp.identity_list:type_name -> turingera.server.robot.Identity
	1,  // 2: turingera.server.robot.GetTagListRsp.tag_list:type_name -> turingera.server.robot.Tag
	0,  // 3: turingera.server.robot.Robot.custom_identity:type_name -> turingera.server.robot.Identity
	1,  // 4: turingera.server.robot.Robot.custom_tag:type_name -> turingera.server.robot.Tag
	10, // 5: turingera.server.robot.Robot.dynamic:type_name -> turingera.server.robot.RobotDynamic
	2,  // 6: turingera.server.robot.RobotDetail.gender:type_name -> turingera.server.robot.Gender
	0,  // 7: turingera.server.robot.RobotDetail.identity_list:type_name -> turingera.server.robot.Identity
	1,  // 8: turingera.server.robot.RobotDetail.tag_list:type_name -> turingera.server.robot.Tag
	9,  // 9: turingera.server.robot.GetRobotRsp.robot:type_name -> turingera.server.robot.Robot
	9,  // 10: turingera.server.robot.GetRobotDetailRsp.robot:type_name -> turingera.server.robot.Robot
	11, // 11: turingera.server.robot.GetRobotDetailRsp.detail:type_name -> turingera.server.robot.RobotDetail
	9,  // 12: turingera.server.robot.NewRobotReq.robot:type_name -> turingera.server.robot.Robot
	9,  // 13: turingera.server.robot.NewRobotRsp.robot:type_name -> turingera.server.robot.Robot
	9,  // 14: turingera.server.robot.EditRobotReq.robot:type_name -> turingera.server.robot.Robot
	9,  // 15: turingera.server.robot.EditRobotRsp.robot:type_name -> turingera.server.robot.Robot
	9,  // 16: turingera.server.robot.GetMyRobotsRsp.robots:type_name -> turingera.server.robot.Robot
	9,  // 17: turingera.server.robot.RecommendRobotsRsp.robots:type_name -> turingera.server.robot.Robot
	10, // 18: turingera.server.robot.UpdateDynamicReq.dynamic:type_name -> turingera.server.robot.RobotDynamic
	3,  // 19: turingera.server.robot.RobotSvr.GetGenderList:input_type -> turingera.server.robot.GetGenderListReq
	5,  // 20: turingera.server.robot.RobotSvr.GetIdentityList:input_type -> turingera.server.robot.GetIdentityListReq
	7,  // 21: turingera.server.robot.RobotSvr.GetTagList:input_type -> turingera.server.robot.GetTagListReq
	12, // 22: turingera.server.robot.RobotSvr.GetRobot:input_type -> turingera.server.robot.GetRobotReq
	14, // 23: turingera.server.robot.RobotSvr.GetRobotDetail:input_type -> turingera.server.robot.GetRobotDetailReq
	16, // 24: turingera.server.robot.RobotSvr.NewRobot:input_type -> turingera.server.robot.NewRobotReq
	18, // 25: turingera.server.robot.RobotSvr.EditRobot:input_type -> turingera.server.robot.EditRobotReq
	20, // 26: turingera.server.robot.RobotSvr.DeleteRobot:input_type -> turingera.server.robot.DeleteRobotReq
	22, // 27: turingera.server.robot.RobotSvr.GetMyRobots:input_type -> turingera.server.robot.GetMyRobotsReq
	24, // 28: turingera.server.robot.RobotSvr.RecommendRobots:input_type -> turingera.server.robot.RecommendRobotsReq
	26, // 29: turingera.server.robot.RobotSvr.RandomRobotID:input_type -> turingera.server.robot.RandomRobotIDReq
	28, // 30: turingera.server.robot.RobotSvr.UpdateDynamic:input_type -> turingera.server.robot.UpdateDynamicReq
	4,  // 31: turingera.server.robot.RobotSvr.GetGenderList:output_type -> turingera.server.robot.GetGenderListRsp
	6,  // 32: turingera.server.robot.RobotSvr.GetIdentityList:output_type -> turingera.server.robot.GetIdentityListRsp
	8,  // 33: turingera.server.robot.RobotSvr.GetTagList:output_type -> turingera.server.robot.GetTagListRsp
	13, // 34: turingera.server.robot.RobotSvr.GetRobot:output_type -> turingera.server.robot.GetRobotRsp
	15, // 35: turingera.server.robot.RobotSvr.GetRobotDetail:output_type -> turingera.server.robot.GetRobotDetailRsp
	17, // 36: turingera.server.robot.RobotSvr.NewRobot:output_type -> turingera.server.robot.NewRobotRsp
	19, // 37: turingera.server.robot.RobotSvr.EditRobot:output_type -> turingera.server.robot.EditRobotRsp
	21, // 38: turingera.server.robot.RobotSvr.DeleteRobot:output_type -> turingera.server.robot.DeleteRobotRsp
	23, // 39: turingera.server.robot.RobotSvr.GetMyRobots:output_type -> turingera.server.robot.GetMyRobotsRsp
	25, // 40: turingera.server.robot.RobotSvr.RecommendRobots:output_type -> turingera.server.robot.RecommendRobotsRsp
	27, // 41: turingera.server.robot.RobotSvr.RandomRobotID:output_type -> turingera.server.robot.RandomRobotIDRsp
	29, // 42: turingera.server.robot.RobotSvr.UpdateDynamic:output_type -> turingera.server.robot.UpdateDynamicRsp
	31, // [31:43] is the sub-list for method output_type
	19, // [19:31] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_robot_proto_init() }
func file_robot_proto_init() {
	if File_robot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_robot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGenderListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGenderListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIdentityListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIdentityListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTagListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTagListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Robot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RobotDynamic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RobotDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRobotReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRobotRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRobotDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRobotDetailRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewRobotReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewRobotRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditRobotReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditRobotRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRobotReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRobotRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyRobotsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMyRobotsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecommendRobotsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecommendRobotsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomRobotIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomRobotIDRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDynamicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_robot_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDynamicRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_robot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_robot_proto_goTypes,
		DependencyIndexes: file_robot_proto_depIdxs,
		MessageInfos:      file_robot_proto_msgTypes,
	}.Build()
	File_robot_proto = out.File
	file_robot_proto_rawDesc = nil
	file_robot_proto_goTypes = nil
	file_robot_proto_depIdxs = nil
}
